# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart_bram.xdc

# IP: ip/block_ram_add/block_ram_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_ram_add || ORIG_REF_NAME==block_ram_add} -quiet] -quiet

# XDC: ip/block_ram_add/block_ram_add_ooc.xdc
