# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/parrot.png.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/imports/new/UART_SDRAM.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/block_image_rom.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/colorlump.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/display_seg.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/switch_resolution.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/imports/new/sync.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/sync_pre.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/imports/new/uart_txd_16.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/imports/new/uart_vga_out.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/vga_move.v}
  {C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/new/index.v}
}
read_ip -quiet {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/block_ram_add/block_ram_add.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/block_ram_add/block_ram_add_ooc.xdc}}]

read_ip -quiet {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/rom/rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/rom/rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/constrs_1/new/uart_bram.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Lori/Documents/Tencent Files/695297502/FileRecv/Index.xpr/bram_uart/bram_uart.srcs/constrs_1/new/uart_bram.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top index -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef index.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file index_utilization_synth.rpt -pb index_utilization_synth.pb"
