# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/administrator/Desktop/constr_1.xdc

# IP: ip/block_ram/block_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_ram || ORIG_REF_NAME==block_ram} -quiet] -quiet

# XDC: ip/block_ram/block_ram_ooc.xdc
