# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart_sdram.xdc

# IP: ip/sdram/sdram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdram || ORIG_REF_NAME==sdram} -quiet] -quiet

# IP: ip/clk_400/clk_400.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_400 || ORIG_REF_NAME==clk_400} -quiet] -quiet

# XDC: ip/sdram/sdram/user_design/constraints/sdram.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdram || ORIG_REF_NAME==sdram} -quiet] -quiet

# XDC: ip/sdram/sdram/user_design/constraints/sdram_ooc.xdc

# XDC: ip/clk_400/clk_400_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_400 || ORIG_REF_NAME==clk_400} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_400/clk_400.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_400 || ORIG_REF_NAME==clk_400} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_400/clk_400_ooc.xdc
