# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/users/administrator/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-364-40628/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.cache/wt [current_project]
set_property parent.project_path C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.srcs/sources_1/imports/Desktop/project_tips/vga_files/parrot.png.coe
read_verilog -library xil_defaultlib {{C:/users/administrator/Documents/Tencent Files/1033690636/FileRecv/uart_txd.v}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.srcs/constrs_1/imports/Desktop/constr_1.xdc
set_property used_in_implementation false [get_files C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.srcs/constrs_1/imports/Desktop/constr_1.xdc]

read_xdc C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.srcs/constrs_1/new/uart0.xdc
set_property used_in_implementation false [get_files C:/users/administrator/Downloads/simple_VGA-master/simple_VGA/project_1.srcs/constrs_1/new/uart0.xdc]


synth_design -top uart_rxd -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_rxd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_rxd_utilization_synth.rpt -pb uart_rxd_utilization_synth.pb"
